/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: array.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "array.pb-c.h"
void   tutorial__entry__init
                     (Tutorial__Entry         *message)
{
  static const Tutorial__Entry init_value = TUTORIAL__ENTRY__INIT;
  *message = init_value;
}
size_t tutorial__entry__get_packed_size
                     (const Tutorial__Entry *message)
{
  assert(message->base.descriptor == &tutorial__entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tutorial__entry__pack
                     (const Tutorial__Entry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tutorial__entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tutorial__entry__pack_to_buffer
                     (const Tutorial__Entry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tutorial__entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tutorial__Entry *
       tutorial__entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tutorial__Entry *)
     protobuf_c_message_unpack (&tutorial__entry__descriptor,
                                allocator, len, data);
}
void   tutorial__entry__free_unpacked
                     (Tutorial__Entry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tutorial__entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tutorial__myset__init
                     (Tutorial__Myset         *message)
{
  static const Tutorial__Myset init_value = TUTORIAL__MYSET__INIT;
  *message = init_value;
}
size_t tutorial__myset__get_packed_size
                     (const Tutorial__Myset *message)
{
  assert(message->base.descriptor == &tutorial__myset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tutorial__myset__pack
                     (const Tutorial__Myset *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tutorial__myset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tutorial__myset__pack_to_buffer
                     (const Tutorial__Myset *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tutorial__myset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tutorial__Myset *
       tutorial__myset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tutorial__Myset *)
     protobuf_c_message_unpack (&tutorial__myset__descriptor,
                                allocator, len, data);
}
void   tutorial__myset__free_unpacked
                     (Tutorial__Myset *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tutorial__myset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tutorial__array__init
                     (Tutorial__Array         *message)
{
  static const Tutorial__Array init_value = TUTORIAL__ARRAY__INIT;
  *message = init_value;
}
size_t tutorial__array__get_packed_size
                     (const Tutorial__Array *message)
{
  assert(message->base.descriptor == &tutorial__array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tutorial__array__pack
                     (const Tutorial__Array *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tutorial__array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tutorial__array__pack_to_buffer
                     (const Tutorial__Array *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tutorial__array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tutorial__Array *
       tutorial__array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tutorial__Array *)
     protobuf_c_message_unpack (&tutorial__array__descriptor,
                                allocator, len, data);
}
void   tutorial__array__free_unpacked
                     (Tutorial__Array *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tutorial__array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tutorial__entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tutorial__Entry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Tutorial__Entry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tutorial__entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange tutorial__entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tutorial__entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tutorial.entry",
  "Entry",
  "Tutorial__Entry",
  "tutorial",
  sizeof(Tutorial__Entry),
  2,
  tutorial__entry__field_descriptors,
  tutorial__entry__field_indices_by_name,
  1,  tutorial__entry__number_ranges,
  (ProtobufCMessageInit) tutorial__entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tutorial__myset__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Tutorial__Myset, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entries",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tutorial__Myset, n_entries),
    offsetof(Tutorial__Myset, entries),
    &tutorial__entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tutorial__myset__field_indices_by_name[] = {
  1,   /* field[1] = entries */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange tutorial__myset__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tutorial__myset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tutorial.myset",
  "Myset",
  "Tutorial__Myset",
  "tutorial",
  sizeof(Tutorial__Myset),
  2,
  tutorial__myset__field_descriptors,
  tutorial__myset__field_indices_by_name,
  1,  tutorial__myset__number_ranges,
  (ProtobufCMessageInit) tutorial__myset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tutorial__array__field_descriptors[1] =
{
  {
    "sets",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tutorial__Array, n_sets),
    offsetof(Tutorial__Array, sets),
    &tutorial__myset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tutorial__array__field_indices_by_name[] = {
  0,   /* field[0] = sets */
};
static const ProtobufCIntRange tutorial__array__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tutorial__array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tutorial.array",
  "Array",
  "Tutorial__Array",
  "tutorial",
  sizeof(Tutorial__Array),
  1,
  tutorial__array__field_descriptors,
  tutorial__array__field_indices_by_name,
  1,  tutorial__array__number_ranges,
  (ProtobufCMessageInit) tutorial__array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
